CREATE TABLE todos (
    todo_id SERIAL PRIMARY KEY,
    task TEXT NOT NULL,
    is_done BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    author_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE
);